version: '3'

services:
  stockapi:
    build: stockapi/
    ports:
      - 8000:8000
    networks:
      - deploy_network
    container_name: stockapi

  stocklit:
    build: stocklit/
    depends_on:
      - stockapi
    ports:
        - 8501:8501
    networks:
      - deploy_network
    container_name: stocklit

networks:
  deploy_network:
    driver: bridge